import { TextEdit, VerticalBox, HorizontalBox, ListView, Button, LineEdit } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 1000px;
    height: 1000px;
    in-out property <string> content: "fail";
    in-out property <[string]> files: ["empty"];
    out property <string> current_file: "example";
    out property <string> new_file: "New";
    out property <string> requested_file;
    out property <string> new_name;
    callback write();
    callback new();
    callback current();
    callback request();
    callback rename();


    popup := PopupWindow {
        close-policy: close-on-click-outside;
        Rectangle {
            height: 100%;
            width: 100%;
            LineEdit {
                placeholder-text: "New Note";
                accepted(text) => {
                    new_file = text;
                    new();
                    popup.close();
                }
            }
        }
        x: 20px;
        y: 20px;
        height: 50px;
        width: 200px;
    }

    popup_2 := PopupWindow {
        close-policy: close-on-click-outside;
        Rectangle {
            height: 100%;
            width: 100%;
            LineEdit {
                placeholder-text: "Note Name";
                accepted(text) => {
                    requested_file = text;
                    request();
                    popup_2.close();
                }
            }
        }
        x: 20px;
        y: 60px;
        height: 50px;
        width: 200px;
    }

    popup_3 := PopupWindow {
        close-policy: close-on-click-outside;
        Rectangle {
            height: 100%;
            width: 100%;
            LineEdit {
                placeholder-text: "Note Name";
                accepted(text) => {
                    new_name = text;
                    rename();
                    popup_3.close();
                }
            }
        }
        x: 20px;
        y: 100px;
        height: 50px;
        width: 200px;
    }

    HorizontalBox {
        spacing: 20px;

        VerticalBox {
            max-width: 200px;
            VerticalBox {
                Button {
                    text: "New Note";
                    clicked => { popup.show(); }
                }
                Button {
                    text: "Request";
                    clicked => { popup_2.show(); }
                }
                Button {
                    text: "Rename";
                    clicked => {popup_3.show(); }
                }
                
            }
            ListView {
                for data in files: Button {
                    height: 30px;
                    width: parent.width;
                    text: data;
                    clicked => {
                        current_file = data;
                        current();
                    }
                }
            }
        }

        VerticalBox {
            TextEdit {
                font-size: 14px;
                text <=> content;
                edited(text) => {
                    debug("text edited: ", current_file);
                }
                key-pressed(event) => {
                    if (event.text == "s" && event.modifiers.control) {
                        write();
                        accept
                    }
                    if (event.text == "escape") {
                        self.clear-focus();
                        accept
                    } else {
                        reject
                    }
                }
            }
        }
    }
}